### ISSUE TITLE
Make multiple "Matches" type methods

### ISSUE THREAD

**Issue by wbratz** [wbratz/NameComparisonToolkit#13]
Something like

Matches, MatchesAny, Contains, MatchesAnyNamePart, NamePartContains
NamePartContainswhich is a shitty name would be FirstName: "Mary Elizabeth"  matches both "Mary" and "Elizabeth"

These would build off of the existing Comparers similar to the addition of Contains

**Comment by billy-bratz** [comment]
Matches ❌ - Should ignore order
MatchesAny ✔
Contains ✔
MatchesIgnoreOrder ❌ - Needs to work how matches works now
