### ISSUE TITLE
Consolidate Matching (Comparers)

### ISSUE THREAD

**Issue by billy-bratz** [wbratz/NameComparisonToolkit#6]
Right now we have first name and last name logic being duplicated in all the comparers. We don't need to do that, instead we should use the last name comparer and the first name comparer in the other comparisons so FirstLast should be a aggregation of First Comparer and last comparer

**Comment by lildevlady** [comment]
wouldn't it just be a single comparer used for each name part that is getting compared in whatever method it is?

**Comment by billy-bratz** [comment]
It could be
